import fs from "node:fs";
import path from "node:path";
import { randomBytes } from "node:crypto";
import { config as loadDotenv, parse as parseEnvFileContents } from "dotenv";
import { updateEnvFileContents, writeEnvFileAtomicallyIfChanged } from "@paperclipai/shared/env-file";
import { resolveConfigPath } from "./store.js";
import { ensureEphemeralAgentJwtSecret, isTruthyEnvFlag } from "./server-secret-hardening.js";

const JWT_SECRET_ENV_KEY = "PAPERCLIP_AGENT_JWT_SECRET";
const PAPERCLIP_OWNED_ENV_KEY_PATTERN = /^PAPERCLIP_[A-Z0-9_]+$/;
const EPHEMERAL_SECRET_ENV_KEY = "PAPERCLIP_AGENT_JWT_SECRET_EPHEMERAL";
// Match the assignments accepted by dotenv, including whitespace around the separator
// and quoted values that span lines. A post-write parse check catches parser drift.
const DOTENV_ASSIGNMENT_PATTERN = /^[^\S\r\n]*(?:export\s+)?([\w.-]+)(?:\s*=\s*?|:\s+?)(\s*'(?:\\'|[^'])*'|\s*"(?:\\"|[^"])*"|\s*`(?:\\`|[^`])*`|[^#\r\n]+)?[^\S\r\n]*(?:#[^\r\n]*)?(?:\r\n|\n|\r|$)/gm;
function resolveEnvFilePath(configPath?: string) {
  return path.resolve(path.dirname(resolveConfigPath(configPath)), ".env");
}
const loadedEnvFiles = new Set<string>();

function isNonEmpty(value: unknown): value is string {
  return typeof value === "string" && value.trim().length > 0;
}

function parseEnvFile(contents: string) {
  try {
    return parseEnvFileContents(contents);
  } catch {
    return {};
  }
}

function emptyEnvFileContents() {
  return [
    "# Paperclip environment variables",
    "# Generated by Paperclip CLI commands",
    "",
  ].join("\n");
}

function paperclipOwnedEntries(entries: Record<string, string>): Record<string, string> {
  return Object.fromEntries(
    Object.entries(entries).filter(
      ([key, value]) => PAPERCLIP_OWNED_ENV_KEY_PATTERN.test(key) && value.trim().length > 0,
    ),
  );
}

export function resolvePaperclipEnvFile(configPath?: string): string {
  return resolveEnvFilePath(configPath);
}

export function resolveAgentJwtEnvFile(configPath?: string): string {
  return resolveEnvFilePath(configPath);
}

export function loadPaperclipEnvFile(configPath?: string): void {
  loadAgentJwtEnvFile(resolveEnvFilePath(configPath));
}

export function loadAgentJwtEnvFile(filePath = resolveEnvFilePath()): void {
  if (loadedEnvFiles.has(filePath)) return;

  if (!fs.existsSync(filePath)) return;
  loadedEnvFiles.add(filePath);
  loadDotenv({ path: filePath, override: false, quiet: true });
}

export function readAgentJwtSecretFromEnv(configPath?: string): string | null {
  loadAgentJwtEnvFile(resolveEnvFilePath(configPath));
  const raw = process.env[JWT_SECRET_ENV_KEY];
  return isNonEmpty(raw) ? raw!.trim() : null;
}

export function readAgentJwtSecretFromEnvFile(filePath = resolveEnvFilePath()): string | null {
  if (!fs.existsSync(filePath)) return null;

  const raw = fs.readFileSync(filePath, "utf-8");
  const values = parseEnvFile(raw);
  const value = values[JWT_SECRET_ENV_KEY];
  return isNonEmpty(value) ? value!.trim() : null;
}

export function isEphemeralAgentJwtSecretEnabled(configPath?: string): boolean {
  loadAgentJwtEnvFile(resolveEnvFilePath(configPath));
  return isTruthyEnvFlag(process.env[EPHEMERAL_SECRET_ENV_KEY]);
}

export function ensureAgentJwtSecret(configPath?: string): { secret: string; created: boolean } {
  if (isEphemeralAgentJwtSecretEnabled(configPath)) {
    return { secret: ensureEphemeralAgentJwtSecret(), created: false };
  }
  const existingEnv = readAgentJwtSecretFromEnv(configPath);
  if (existingEnv) {
    return { secret: existingEnv, created: false };
  }

  const envFilePath = resolveEnvFilePath(configPath);
  const existingFile = readAgentJwtSecretFromEnvFile(envFilePath);
  const secret = existingFile ?? randomBytes(32).toString("hex");
  const created = !existingFile;

  if (!existingFile) {
    writeAgentJwtEnv(secret, envFilePath);
  }

  return { secret, created };
}

export function writeAgentJwtEnv(secret: string, filePath = resolveEnvFilePath()): void {
  mergePaperclipEnvEntries({ [JWT_SECRET_ENV_KEY]: secret }, filePath);
}

export function readPaperclipEnvEntries(filePath = resolveEnvFilePath()): Record<string, string> {
  if (!fs.existsSync(filePath)) return {};
  return parseEnvFile(fs.readFileSync(filePath, "utf-8"));
}

export function writePaperclipEnvEntries(entries: Record<string, string>, filePath = resolveEnvFilePath()): void {
  const previousContents = fs.existsSync(filePath) ? fs.readFileSync(filePath, "utf8") : null;
  const nextContents = updateEnvFileContents(previousContents ?? emptyEnvFileContents(), paperclipOwnedEntries(entries), {
    valueEncoding: "minimal",
  });
  writeEnvFileAtomicallyIfChanged(filePath, previousContents, nextContents);
}

export function removeAgentJwtSecretFromEnvFile(filePath = resolveEnvFilePath()): void {
  if (!fs.existsSync(filePath)) return;
  const previousContents = fs.readFileSync(filePath, "utf8");
  const nextContents = previousContents.replace(DOTENV_ASSIGNMENT_PATTERN, (match, key: string) =>
    key === JWT_SECRET_ENV_KEY ? "" : match,
  );
  if (Object.hasOwn(parseEnvFile(nextContents), JWT_SECRET_ENV_KEY)) {
    throw new Error("Cannot remove agent JWT signing secret from env file");
  }
  writeEnvFileAtomicallyIfChanged(filePath, previousContents, nextContents);
  if (Object.hasOwn(readPaperclipEnvEntries(filePath), JWT_SECRET_ENV_KEY)) {
    throw new Error("Agent JWT signing secret remains in env file after removal");
  }
}

export function mergePaperclipEnvEntries(
  entries: Record<string, string>,
  filePath = resolveEnvFilePath(),
): Record<string, string> {
  const current = readPaperclipEnvEntries(filePath);
  const managedEntries = paperclipOwnedEntries(entries);
  const next = {
    ...current,
    ...managedEntries,
  };
  writePaperclipEnvEntries(managedEntries, filePath);
  return next;
}
